apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e-banking
  namespace: e-banking-front
spec:
  project: e-banking
  source:
    repoURL: https://github.com/Khadija-Laamiri/e-banking-front-manifest
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: e-banking-front
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true