apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-banking-app
  template:
    metadata:
      labels:
        app: e-banking-app
    spec:
      containers:
        - name: e-banking-app
          image: laamirikhadija/e-banking-front:07a0e686199dc3e1b7f7185ed9a9aa9373cabd92
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
