apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-banking-app
  template:
    metadata:
      labels:
        app: e-banking-app
    spec:
      containers:
        - name: e-banking-app
          image: laamirikhadija/e-banking-front:d1b6a22598f54c2c0446481ee63855ece6d959f0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
