apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-banking-app
  template:
    metadata:
      labels:
        app: e-banking-app
    spec:
      containers:
        - name: e-banking-app
          image: laamirikhadija/e-banking-front:ecaf38265f3f0c3c03cf1fab2c2743ffddac40ac
          imagePullPolicy: Always
          ports:
            - containerPort: 80
