apiVersion: v1
kind: Service
metadata:
  name: e-banking-app
spec:
  type: NodePort
  selector:
    app: e-banking-app
  ports:
    - port: 4002
      protocol: TCP
      targetPort: 4002
      nodePort: 31000
